$schemaver: '2.0'
repo_url: https://github.com/byu-oit/swagger-enforcer
software:
  - name: swagger-enforcer
    type: Library
    aliases:
    short_description: Automatically validate swagger objects while you build them
      and/or validate the final object.
    assignment_group: gro:AD-Miscellaneous Information Applications
    notes:
    maintained_by:
      - Gi60s
    developed_by_byu: true
    ddd:
      business_domain:
      ubiquitous_language_url:
      context_map_url:
    links:
      system_documentation_url: https://github.com/byu-oit/swagger-enforcer
      swagger_urls:
    microservice: false
    technologies_used:
      - JavaScript
      - NodeJS
      - Travis-ci.com
    stages:
      production:
        urls:
          product_page: https://github.com/byu-oit/swagger-enforcer
          physical_url:
          virtual_url:
        hosting_location:
        aws_account:
        relationships:
          depends_on:
            db_read_write:
            db_read_only:
            software:
          supports:
            software:
            service:
          reverse_proxy:
          runs_on:
            server_cluster:
            virtual_server:
            rack_server:
            blade_server:
    tags:
      data-sensitivity: confidential
      app: swagger-enforcer
      team: gro:AD-Miscellaneous Information Applications
